// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Platformu tespit et ve uygun config'i döndür
    return android;
    // return ios; // iOS için
    // return web; // Web için
  }

  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
      appId: dotenv.env['FIREBASE_ANDROID_APP_ID'] ?? '',
      messagingSenderId:
          dotenv.env['FIREBASE_ANDROID_MESSAGING_SENDER_ID'] ?? '',
      projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'focusly-9e177',
      databaseURL: dotenv.env['FIREBASE_ANDROID_DATABASE_URL'],
      storageBucket: dotenv.env['FIREBASE_ANDROID_STORAGE_BUCKET'],
    );
  }

  static FirebaseOptions get ios {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
      appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '',
      messagingSenderId: dotenv.env['FIREBASE_IOS_MESSAGING_SENDER_ID'] ?? '',
      projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'focusly-9e177',
      databaseURL: dotenv.env['FIREBASE_IOS_DATABASE_URL'],
      storageBucket: dotenv.env['FIREBASE_IOS_STORAGE_BUCKET'],
      iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'],
    );
  }

  static FirebaseOptions get web {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
      appId: dotenv.env['FIREBASE_WEB_APP_ID'] ?? '',
      messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '',
      projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'focusly-9e177',
      authDomain: dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'],
      storageBucket: dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'],
      measurementId: dotenv.env['FIREBASE_WEB_MEASUREMENT_ID'],
    );
  }
}
